id: P009655
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:43:04.737610
source_metadata:
  id: bdr:W3CN8805
  title: ཆག་ལོ་ཙཱ་བ་ཆོས་རྗེ་དཔལ་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    0042aac8a5484ee7bc56920ddf0735d8:
      image_group_id: I3CN8807
      title: ''
      volume_number: 1
      total_pages: 130
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
