id: IA5AE6FAB
legacy_id: P009655
ocr_import_info:
  bdrc_scan_id: W3CN8805
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T20:29:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T17:04:27.804581+00:00'
last_modified: 2022-09-04 01:04:35.149289
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN8805
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN8805
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆག་ལོ་ཙཱ་བ་ཆོས་རྗེ་དཔལ་གྱི་རྣམ་ཐར།
statistics:
  ocr_word_mean_confidence_index: 0.8089970608409492
  ocr_word_median_confidence_index: 0.8799999952316284
quality: null
bases:
  I3CN8807:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN8807
      total_pages: 130
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN8807.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.8089970608409492
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
